version: '3'
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: variety_user
      POSTGRES_PASSWORD: Variety@Password
      POSTGRES_DB: variety-db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: